### ISSUE TITLE
nix build ".#hydraJobs.duos": ../arch/riscv/mm/context.c:67: Error: unknown CSR `sptbr'

### ISSUE THREAD

**Issue by devurandom** [NickCao/nixos-riscv#23]
I tried to build an image for the Milk-V Duo S:
```
$ gh repo clone NickCao/nixos-riscv
$ cd nixos-riscv
$ nix build ".#hydraJobs.duos"
```

But the build fails with errors that seem identical with the ones in https://hydra.nichi.co/build/994258/nixlog/12:
```
[...]
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
manual-config configurePhase buildRoot=/build/linux_5.10/build pwd=/build/linux_5.10
'/build/linux_5.10/build/.config' -> '/nix/store/r5wh1fjy8cf39gmy2dj9h7zxggcvr5sl-milkv-duo-256-linux-config'
.config:259:warning: override: reassigning to symbol ENABLE_MUST_CHECK
*
* Restart config...
*
[...]
*
* Control Group support
*
Control Group support (CGROUPS) [Y/n/?] y
  Memory controller (MEMCG) [Y/n/?] y
  IO controller (BLK_CGROUP) [N/y/?] (NEW) 
Error in reading or end of file.

  *
  * CPU controller
  *
  CPU controller (CGROUP_SCHED) [Y/n/?] y
    Group scheduling for SCHED_OTHER (FAIR_GROUP_SCHED) [Y/n/?] (NEW) 
Error in reading or end of file.

[...]
../arch/riscv/mm/context.c: Assembler messages:
../arch/riscv/mm/context.c:67: Error: unknown CSR `sptbr'
make[3]: *** [../scripts/Makefile.build:279: arch/riscv/mm/context.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [../scripts/Makefile.build:496: arch/riscv/mm] Error 2
make[2]: *** Waiting for unfinished jobs....
[...]
make: *** [../Makefile:185: __sub-make] Error 2
```

[nix log /nix/store/xhx8w20982j2k7ii2ccb9i8x1gypi7rd-linux-riscv64-unknown-linux-gnu-5.10.4.drv](https://github.com/user-attachments/files/18547040/xhx8w20982j2k7ii2ccb9i8x1gypi7rd-linux-riscv64-unknown-linux-gnu-5.10.4.drv.log)

**Comment by NickCao** [comment]
The kernel config error is fine, the actual problem is
```
../arch/riscv/mm/context.c:67: Error: unknown CSR `sptbr'
```
It has been this way since the last gcc/binutils upgrade and there's no easy fix.

**Comment by devurandom** [comment]
Thanks for noticing this.  I missed it among the plethora of warnings.

Possibly related:
* https://github.com/riscv-non-isa/riscv-arch-test/issues/107#issuecomment-881976236
* https://github.com/riscv-software-src/riscv-tests/pull/578#issue-2465606688

In their essence both agree: `sptbr` was renamed to `satp`.

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/riscv/mm/context.c?h=v5.10.4#n67 is a closing brace and the file looks quite different from the file being build, `/nix/store/568ij6c6xzn41ny03iwskdqwd6pa638m-source/linux_5.10/arch/riscv/mm/context.c`.  But the file we're building with uses `sptbr` instead of `satp`:
```
❯ rg -i sptbr /nix/store/568ij6c6xzn41ny03iwskdqwd6pa638m-source/linux_5.10/arch/riscv/mm/context.c
67:	csr_write(sptbr, virt_to_pfn(next->pgd) | SATP_MODE | asid);
```

The kernel was updated to use `satp` instead of `sptbr` in several locations, but not in calls to `csr_write`: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.10.4&id=7549cdf59d9fafbaab42650375c29c64c16aa270
Reason mentioned was a binutils version that would not yet know about the new name.

https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=767a879e31ce31179e6135c2f991f670a35709fa mentions:
> 2. Only creates aliases for registers that are actually present on
> the target (as announced in the target XML description).

Is it possible that "the target XML description" changed and no longer mentions the old register names?

**Comment by NickCao** [comment]
I believe the current upstream kernel has already renamed all occurrences of  `sptbr`, but the duo's vendor kernel is forever stuck on 5.10.

**Comment by devurandom** [comment]
> the duo's vendor kernel is forever stuck on 5.10.

Why?  (Honest question, since I'm probably missing something.)

https://github.com/sophgo/linux/wiki#cv18xx-series suggests that with kernel versions 6.12 / 6.13 many patches are merged already, and patches for most of the missing bits exist.  Would it be possible to port them to 6.13 and try from there, instead of trying to get 5.10.4 to work with recent tools?

**Comment by NickCao** [comment]
> Why? (Honest question, since I'm probably missing something.)

That's the unfortunate nature of how most vendors work with their SoCs, just like with android phones, they'd never bother to rebase onto a newer kernel version.

> https://github.com/sophgo/linux/wiki#cv18xx-series suggests that with kernel versions 6.12 / 6.13 many patches are merged already, and patches for most of the missing bits exist. Would it be possible to port them to 6.13 and try from there, instead of trying to get 5.10.4 to work with recent tools?

Yes, as long as someone is willing to make the effort. One particularity with the duo family is their tiny memory, you have to tailor the kernel config to cut out all the unnecessary bits so it fits.

**Comment by NickCao** [comment]
Fixed by https://github.com/NickCao/nixos-riscv/pull/24, well that's embarrassing, the fix was surprisingly simple.

**Comment by devurandom** [comment]
Mine is a [Duo S](https://github.com/NickCao/nixos-riscv/blob/master/duos.nix).  The issue persists.

**Comment by NickCao** [comment]
Try https://github.com/NickCao/nixos-riscv/commit/e6c8b0bceafe7ea736935bc84d3418f4137b3fa5

**Comment by devurandom** [comment]
Hydra succeeded: https://hydra.nichi.co/build/999376
Worked also locally. Thanks!
